
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Authenticated } from "convex/react"

import "./globals.css";
import AuthProvider from "@/components/auth-provider";
import { NavigationMenuDemo } from "@/components/Navbar";
import { UserButton } from "@clerk/nextjs";
import { Separator } from "@/components/ui/separator";
import {Toaster} from "@/components/ui/sonner"
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
        
        className="">
            <NavigationMenuDemo />      
            
          </div>
          <Separator />

       
       
        {children}
        <Toaster />
      </body>
      </AuthProvider>
    </html>
  );
}
